#############################################################################
# Makefile for building: bluetooth
# Generated by qmake (2.01a) (Qt 4.6.2) on: Fri Mar 16 05:49:19 2012
# Project:  bluetooth.pro
# Template: app
# Command: /usr/local/Trolltech/Qt-embedded-4.6.2/bin/qmake -unix -o Makefile bluetooth.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/qws/linux-arm-g++ -I. -I/usr/local/Trolltech/Qt-embedded-4.6.2/include/QtCore -I/usr/local/Trolltech/Qt-embedded-4.6.2/include/QtNetwork -I/usr/local/Trolltech/Qt-embedded-4.6.2/include/QtGui -I/usr/local/Trolltech/Qt-embedded-4.6.2/include -I. -Iserver -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/Qt-embedded-4.6.2/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/Qt-embedded-4.6.2/lib -lts -lQtGui -L/home/sprife/work/QT4.6_NO_CURSOR/qt-everywhere-opensource-src-4.6.2_nocursor/../tslib1.4-install/lib -L/usr/local/Trolltech/Qt-embedded-4.6.2/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/Qt-embedded-4.6.2/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwidget.cpp \
		mylabel.cpp \
		zigbeetopo.cpp \
		server/cliect_td.cpp moc_mainwidget.cpp \
		moc_mylabel.cpp \
		moc_zigbeetopo.cpp \
		moc_cliect_td.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwidget.o \
		mylabel.o \
		zigbeetopo.o \
		cliect_td.o \
		moc_mainwidget.o \
		moc_mylabel.o \
		moc_zigbeetopo.o \
		moc_cliect_td.o \
		qrc_images.o
DIST          = /usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/qws.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/include_source_dir.prf \
		bluetooth.pro
QMAKE_TARGET  = bluetooth
DESTDIR       = 
TARGET        = bluetooth

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: bluetooth.pro  /usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/qws/linux-arm-g++/qmake.conf /usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/g++.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/unix.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/linux.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/qws.conf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/qconfig.pri \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/release.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/moc.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/resources.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/uic.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/lex.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtGui.prl \
		/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtNetwork.prl \
		/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile bluetooth.pro
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/g++.conf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/unix.conf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/linux.conf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/common/qws.conf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/qconfig.pri:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/release.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/default_post.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/qt.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/moc.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/resources.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/uic.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/yacc.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/lex.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtGui.prl:
/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtNetwork.prl:
/usr/local/Trolltech/Qt-embedded-4.6.2/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile bluetooth.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/bluetooth1.0.0 || $(MKDIR) .tmp/bluetooth1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/bluetooth1.0.0/ && $(COPY_FILE) --parents mainwidget.h mylabel.h zigbeetopo.h server/api.h server/cliect_td.h server/zigbee_struct.h .tmp/bluetooth1.0.0/ && $(COPY_FILE) --parents images/images.qrc .tmp/bluetooth1.0.0/ && $(COPY_FILE) --parents main.cpp mainwidget.cpp mylabel.cpp zigbeetopo.cpp server/cliect_td.cpp .tmp/bluetooth1.0.0/ && $(COPY_FILE) --parents mainwidget.ui .tmp/bluetooth1.0.0/ && (cd `dirname .tmp/bluetooth1.0.0` && $(TAR) bluetooth1.0.0.tar bluetooth1.0.0 && $(COMPRESS) bluetooth1.0.0.tar) && $(MOVE) `dirname .tmp/bluetooth1.0.0`/bluetooth1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/bluetooth1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwidget.cpp moc_mylabel.cpp moc_zigbeetopo.cpp moc_cliect_td.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwidget.cpp moc_mylabel.cpp moc_zigbeetopo.cpp moc_cliect_td.cpp
moc_mainwidget.cpp: zigbeetopo.h \
		server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h \
		mylabel.h \
		mainwidget.h
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/moc $(DEFINES) $(INCPATH) mainwidget.h -o moc_mainwidget.cpp

moc_mylabel.cpp: server/api.h \
		server/zigbee_struct.h \
		mylabel.h
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/moc $(DEFINES) $(INCPATH) mylabel.h -o moc_mylabel.cpp

moc_zigbeetopo.cpp: server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h \
		zigbeetopo.h
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/moc $(DEFINES) $(INCPATH) zigbeetopo.h -o moc_zigbeetopo.cpp

moc_cliect_td.cpp: server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/moc $(DEFINES) $(INCPATH) server/cliect_td.h -o moc_cliect_td.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images/images.qrc \
		images/02.jpg \
		images/up_wsn_bg2.jpg
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/rcc -name images images/images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwidget.h
ui_mainwidget.h: mainwidget.ui
	/usr/local/Trolltech/Qt-embedded-4.6.2/bin/uic mainwidget.ui -o ui_mainwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwidget.h \
		zigbeetopo.h \
		server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h \
		mylabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwidget.o: mainwidget.cpp mainwidget.h \
		zigbeetopo.h \
		server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h \
		mylabel.h \
		ui_mainwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwidget.o mainwidget.cpp

mylabel.o: mylabel.cpp mylabel.h \
		server/api.h \
		server/zigbee_struct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mylabel.o mylabel.cpp

zigbeetopo.o: zigbeetopo.cpp zigbeetopo.h \
		server/api.h \
		server/zigbee_struct.h \
		server/cliect_td.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zigbeetopo.o zigbeetopo.cpp

cliect_td.o: server/cliect_td.cpp server/cliect_td.h \
		server/api.h \
		server/zigbee_struct.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cliect_td.o server/cliect_td.cpp

moc_mainwidget.o: moc_mainwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwidget.o moc_mainwidget.cpp

moc_mylabel.o: moc_mylabel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mylabel.o moc_mylabel.cpp

moc_zigbeetopo.o: moc_zigbeetopo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_zigbeetopo.o moc_zigbeetopo.cpp

moc_cliect_td.o: moc_cliect_td.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cliect_td.o moc_cliect_td.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

